import json
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, ConfigDict, Field


class CodeFile(BaseModel):
    """Represents a single source code or configuration file generated by Coder Agent."""
    path: str = Field(..., description="Relative file path (e.g. server.py, requirements.txt)")
    content: str = Field(..., description="Raw text/code content of the file")


class MCPBundle(BaseModel):
    """Input contract supplied by Person 1's compiler pipeline."""

    model_config = ConfigDict(populate_by_name=True)

    server_py: str = Field(..., alias="server.py")
    requirements_txt: str = Field(..., alias="requirements.txt")
    test_protocol: Dict[str, Any] = Field(..., alias="test_protocol.json")
    run_tests_py: str = Field(..., alias="run_tests.py")
    env_vars: Dict[str, str] = Field(default_factory=dict)

    def to_coder_output(self) -> "CoderOutput":
        """Convert the shared MCPBundle into the Deployer's internal payload."""
        service_name = self.test_protocol.get("service_name", "mcp-server")
        return CoderOutput(
            project_name=f"{service_name}-mcp-server",
            files=[
                CodeFile(path="server.py", content=self.server_py),
                CodeFile(path="requirements.txt", content=self.requirements_txt),
                CodeFile(
                    path="test_protocol.json",
                    content=json.dumps(self.test_protocol, indent=2),
                ),
                CodeFile(path="run_tests.py", content=self.run_tests_py),
            ],
            entrypoint_file="server.py",
            env_vars=self.env_vars,
            test_commands=["python run_tests.py"],
            test_protocol=self.test_protocol,
        )


class CoderOutput(BaseModel):
    """The structured data contract received from Agent 2 (Coder)."""
    project_name: str = Field(default="mcp-server-project", description="Name of the MCP server project")
    language: str = Field(default="python", description="Programming language: 'python' or 'typescript'")
    runtime_version: str = Field(default="3.11", description="Runtime version (e.g. '3.11', '20')")
    files: List[CodeFile] = Field(..., description="Array of code files generated by Coder Agent")
    entrypoint_file: str = Field(default="server.py", description="Main file to launch the server")
    env_vars: Dict[str, str] = Field(default_factory=dict, description="Environment variables needed at runtime")
    test_commands: List[str] = Field(
        default_factory=list,
        description="Optional list of custom test commands to run inside sandbox"
    )
    test_protocol: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional MCP functional-test protocol supplied by Person 1"
    )


class DeployerOutput(BaseModel):
    """The structured handoff payload sent from Deployer Agent to Tester Agent."""

    # Allow non-serializable objects (e.g. live sandbox manager handle) without Pydantic crashing
    model_config = {"arbitrary_types_allowed": True}

    workspace_id: str = Field(..., description="Unique ID of the provisioned Daytona sandbox workspace")
    status: str = Field(..., description="Deployment status: 'DEPLOYED' or 'DEPLOYMENT_FAILED'")
    project_name: str = Field(..., description="Name of the project deployed")
    language: str = Field(..., description="Language of the workspace")
    entrypoint_file: str = Field(..., description="Main server entrypoint file")
    deployed_files: List[str] = Field(default_factory=list, description="List of file paths uploaded to sandbox")
    env_vars: Dict[str, str] = Field(default_factory=dict, description="Active environment variables")
    test_commands: List[str] = Field(default_factory=list, description="Commands ready for execution by Tester Agent")
    test_protocol: Optional[Dict[str, Any]] = Field(
        default=None,
        description="MCP test protocol handed to the Tester Agent"
    )
    error_message: Optional[str] = Field(default=None, description="Error detail if deployment failed")
    raw_workspace_handle: Optional[Any] = Field(default=None, description="Active workspace client object reference")
